export type RegistrationParamsFilters = {
    page?: number;
    page_size?: number;
    status?: "pending"|"approved"|"rejected";
    risk_aggressive_behavior?: boolean;
    risk_suicidal_selfharm?: boolean;
    risk_substance_abuse?: boolean;
    risk_psychiatric_issues?: boolean;
    risk_criminal_history?: boolean;
    risk_flight_behavior?: boolean;
    risk_weapon_possession?: boolean;
    risk_sexual_behavior?: boolean;
    risk_day_night_rhythm?: boolean;
  } 
  export type Registration = {
      application_date: string;
      application_reason: string;
      care_ambulatory_guidance: boolean;
      care_assisted_independent_living: boolean;
      care_protected_living: boolean;
      care_room_training_center: boolean;
      client_bsn_number: string;
      client_city: string;
      client_email: string;
      client_first_name: string;
      client_gender: string;
      client_goals: string;
      client_house_number: string;
      client_last_name: string;
      client_nationality: string;
      client_phone_number: string;
      client_postal_code: string;
      client_street: string;
      created_at: string;
      document_action_plan: string;
      document_diagnosis: string;
      document_education_report: string;
      document_id_copy: string;
      document_psychiatric_report: string;
      document_referral: string;
      document_safety_plan: string;
      education_additional_notes: string;
      education_currently_enrolled: boolean;
      education_institution: string;
      education_mentor_email: string;
      education_mentor_name: string;
      education_mentor_phone: string;
      education_level: "primary" | "secondary" | "higher" | "none";
      form_status: string;
      guardian1_email: string;
      guardian1_first_name: string;
      guardian1_last_name: string;
      guardian1_phone_number: string;
      guardian1_relationship: string;
      guardian2_email: string;
      guardian2_first_name: string;
      guardian2_last_name: string;
      guardian2_phone_number: string;
      guardian2_relationship: string;
      id: number;
      processed_at: string;
      processed_by_employee_id?: number;
      referrer_email: string;
      referrer_first_name: string;
      referrer_job_title: string;
      referrer_last_name: string;
      referrer_organization: string;
      referrer_phone_number: string;
      referrer_signature: boolean;
      risk_additional_notes: string;
      risk_aggressive_behavior: boolean;
      risk_count: number;
      risk_criminal_history: boolean;
      risk_day_night_rhythm: boolean;
      risk_flight_behavior: boolean;
      risk_other: boolean;
      risk_other_description: string;
      risk_psychiatric_issues: boolean;
      risk_sexual_behavior: boolean;
      risk_substance_abuse: boolean;
      risk_suicidal_selfharm: boolean;
      risk_weapon_possession: boolean;
      submitted_at: string;
      updated_at: string;
      work_additional_notes: string,
      work_current_employer: string,
      work_current_position: string,
      work_currently_employed: boolean,
      work_employer_email: string,
      work_employer_phone: string,
      work_start_date: string
  }