import fs from "fs";
import path from "path";

const APP_DIR = path.resolve(__dirname, "..", "app");
const OUT_FILE = path.resolve(__dirname, "..", "utils", "route-config-nl.generated.ts");

function isGroupDir(name: string) {
  return name.startsWith("("); // Next.js group folders
}

function walk(dir: string, segments: string[] = [], routes = new Set<string>()) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (isGroupDir(entry.name)) {
        walk(path.join(dir, entry.name), segments, routes);
      } else {
        walk(path.join(dir, entry.name), [...segments, entry.name], routes);
      }
    } else if (entry.isFile()) {
      if (/^page\.(t|j)sx?$/.test(entry.name)) {
        const route = segments.length === 0 ? "/" : "/" + segments.join("/");
        routes.add(route);
      }
    }
  }
  return routes;
}

function prettifyLabel(route: string) {
  if (route === "/") return "";
  return route
    .split("/")
    .filter(Boolean)
    .map(seg => {
      if (/^\[.*\]$/.test(seg)) return seg; // keep dynamic segments like [id]
      return seg
        .replace(/-/g, " ")
        .split(" ")
        .map(w => w.charAt(0).toUpperCase() + w.slice(1))
        .join(" ");
    })
    .join(" / ");
}

function generate() {
  if (!fs.existsSync(APP_DIR)) {
    console.error("app/ directory not found at", APP_DIR);
    process.exit(1);
  }
  const routes = Array.from(walk(APP_DIR)).sort();
  const mapping: Record<string, string> = {};
  for (const r of routes) {
    mapping[r] = prettifyLabel(r);
  }

  const fileContent = `// This file is auto-generated by scripts/generate-route-config.ts
/* eslint-disable */
export const routeConfigNL: { [key: string]: string } = ${JSON.stringify(mapping, null, 2)};
export default routeConfigNL;
`;
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, fileContent, "utf8");
  console.log("Wrote", OUT_FILE, "with", routes.length, "routes");
}

generate();